name: btgproject
description: "BTG Challenge App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.2.3
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mocks/funds.json
    - assets/mocks/user.json
    - assets/mocks/investments.json
    - assets/mocks/transactions.json
